#!/bin/zsh
# ADAPTED FROM: https://rowannicholls.github.io/bash/intro/passing_arguments.html
#
# Set defaults
#
port="8080"
#
# Handle command line arguments passed
#
while [[ "$#" -gt 0 ]]
do case $1 in
    -p|--port) port="$2"
    shift;;
    *) echo "Unknown parameter passed: $1"
    exit 1;;
esac
shift
done
#
# Preview the site
#
npx quartz build --serve --port=$port